[package]
name = "labelme-rs"
version.workspace = true
edition.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0"
image = { version="0.24", default-features = false, features = ["png", "jpeg"] }
zune-jpeg = "0.3"
base64 = "0.21"
svg = "0"
indexmap = { version="1", features = ["serde"] }