[workspace]
members = [
    "labelme-rs",
    "app",
    "lmrspy",
]
default-members=["app"]

[workspace.package]
version = "0.5.0"
authors = ["Yuki SUZUKI <y-suzuki@radiol.med.osaka-u.ac.jp>"]
edition = "2021"
repository = "https://github.com/ykszk/labelme-rs"
description = """
My utility tools for labelme.
Check the repository (https://github.com/ykszk/labelme-rs) for details.
"""

[profile.release]
strip = true
