[package]
name = "labelme-rs"
version = "0.4.0"
authors = ["Yuki SUZUKI <y-suzuki@radiol.med.osaka-u.ac.jp>"]
edition = "2021"
repository = "https://github.com/ykszk/labelme-rs"

[workspace]

members = [
    "app",
    "lmrspy",
]

[profile.release]
strip = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0"
image = { version="0.24", default-features = false, features = ["png", "jpeg"] }
base64 = "0.13.0"
svg = "0"
indexmap = { version="1", features = ["serde"] }