[package]
name = "app"
version = "0.3.3"
edition = "2021"

[[bin]]
name = "lm2svg"
path = "src/lm2svg.rs"

[[bin]]
name = "lms2html"
path = "src/lms2html.rs"

[[bin]]
name = "lm_swap_prefix"
path = "src/swap_prefix.rs"

[lib]
name = "dsl"
path = "src/dsl.rs"

[[bin]]
name = "lm_validate"
path = "src/validate.rs"

[dependencies]
labelme-rs = { path = ".."}
clap = { version = "3", features = ["derive"] }
regex = "1"
tera = { version = "1", default-features = false }
log = "0"
env_logger = "0.9"
glob = "0"
indicatif = "0.16"
chumsky = "0"
num_cpus = "1"