name: Rust

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --package app
    - name: Run tests
      run: cargo test --release --all

    - name: Package for windows
      id: create_package
      run: |
        powershell Compress-Archive -Path target/release/*.exe -DestinationPath labelme-rs-${{github.ref_name}}.zip
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        files: |
          labelme-rs-${{github.ref_name}}.zip
